### ISSUE TITLE
Resize disk after cloning

### ISSUE THREAD

**Issue by EyesIce** [UntouchedWagons/Ubuntu-CloudInit-Docs#5]
Hi,
Is it possibile to create an .img based on lvm?
I want to be able to resize disk space after cloning template into vm.

Thank you

**Comment by UntouchedWagons** [comment]
If I understand what you want correctly proxmox and cloudinit handle that automatically. If your template vm has an 8gb disk and you clone it then resize the clone's drive to be 60gb the root file system will be resized for you.

**Comment by EyesIce** [comment]
> If I understand what you want correctly proxmox and cloudinit handle that automatically. If your template vm has an 8gb disk and you clone it then resize the clone's drive to be 60gb the root file system will be resized for you.
> […](#)
> On Nov 4, 2024, 11:11 AM, at 11:11 AM, EyesIce ***@***.***> wrote: Hi, Is it possibile to create an .img based on lvm? I want to be able to resize disk space after cloning template into vm. Thank you -- Reply to this email directly or view it on GitHub: #5 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

Yes, you got it! I'm sorry but I'm new in proxmox and don't know everything. I'm learning on the job. Thank you for your suggestion
